#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SHOOTING_COOLDOWN 10000000
#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240
#define CLOCK_SPEED_DIV 100000
#define PROJECTILE_WIDTH 2
#define MAX_NUM_PROJECTILES 5

#endif